---
title: "PUMPS"
author: "RC"
date: "2024-02-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Hourly volume data 

```{r}
# files in file sharefile folder name"Agua Central 2023"
df<-do.call(rbind, list(X2023_01_Contagens_Agua, X2023_02_Contagens_Agua, X2023_03_Contagens_Agua, X2023_04_Contagens_Agua, X2023_05_Contagens_Agua,X2023_06_Contagens_Agua, X2023_07_Contagens_Agua, X2023_08_Contagens_Agua, X2023_09_Contagens_Agua, X2023_10_Contagens_Agua, X2023_11_Contagens_Agua, X2023_12_Contagens_Agua))
write_excel_csv(df, "volume_bombeado_day_2023.csv") # consumos diários 

df$dia_hora<-as.POSIXct(df$`Data Hora`,format="%d/%m/%Y %H:%M")
df <- df[order(df$dia_hora),]

library(data.table)
setDT(df)[, GRAV := df$`BP1 Grav Contador-Acc 1` - shift(df$`BP1 Grav Contador-Acc 1`)]
setDT(df)[, PRESS := df$`BP1 Bomb Contador-Acc 1` - shift(df$`BP1 Bomb Contador-Acc 1`)]
max(df$PRESS, na.rm = TRUE) #to find out day of major consumption
min(df$PRESS, na.rm = TRUE) #to find out day of minor consumption (dia de limpeza do reservatório 24 & 25 novembro)
df[which(df$PRESS==max(df$PRESS, na.rm = TRUE)),]

```

## peak flow data (no equal time period) dias de menor e maior consumo
```{r}
library(readxl)
jan2<- read_excel("C:/Users/regin/Desktop/ShareFiles/Pump_Station_Capacity/A_Bombas_Amperes_Pressao_Caudal_02e03Janeiro2023.xlsx")
ago5<- read_excel("C:/Users/regin/Desktop/ShareFiles/Pump_Station_Capacity/B_Bombas_Amperes_Pressao_Caudal_04_05_Agosto2023.xlsx")


```

## Duration Diagram

```{r}
library(dplyr)
library(lubridate)
ago5$date<-as.POSIXct(ago5$`Data-Hora`,format="%Y-%m-%d %H:%M:%S")
ago5$minute10<-round_date(ago5$date, unit="10 minutes")

# verificar se o intervalo entre leituras é superior a 10 minutos
ago5<- ago5[order(ago5$date),]
check<-ago5 %>% 
  mutate(diff = date - lag(date),
         diff_minutes = as.numeric(diff, units = "mins"),
         time_int = format(.POSIXct(diff_minutes*60, "UTC"), "%H:%M:%S")) %>% 
  select(date, diff_minutes, time_int) %>% 
  # Filter the data for a range of minutes
  filter(diff_minutes > 10 )

# average flow between readings
library(data.table)
ago5<-as.data.table(ago5)
ago5<-ago5[,Flow10:=mean(`BP1 Bomb Contador-Caudal actua (m3/h)`, na.rm=TRUE), by="minute10"] 

ago5plot<-ago5[, c("minute10","Flow10")]
ago5plot<-ago5plot[!duplicated(ago5plot)]

plot5<-ago5plot$Flow10
plot5<- sort(plot5, decreasing = T)
plot5 <- data.frame(x = 100/length(plot5) * 1:length(plot5), y = plot5)

# repetir para 2 jan


library(ggplot2)
plot_ago_jan<-ggplot() + 
geom_line(data = plot2, aes(x = x, y = y), color = "green") +
 geom_line(data = plot5, aes(x = x, y = y), color = "orange") +
  xlab('% tempo que determinado caudal é igualado ou excedido') +
  ylab('caudal (m3/h)')


```

# Quadro de gamas de caudal versus pressão (S_monitor) à saída da EE


```{r}
library(readxl)
ago5<- read_excel("C:/Users/regin/Desktop/ShareFiles/Pump_Station_Capacity/B_Bombas_Amperes_Pressao_Caudal_04_05_Agosto2023.xlsx")
# to round to the nearest  hour
library(lubridate)
ago5$date<-as.POSIXct(ago5$`Data-Hora`,format="%Y-%m-%d %H:%M:%S", tz="GMT")
ago5$hourly<-round_date(ago5$date, unit="1 hour")
ago5$hour<-ago5$hour<-format(ago5$date,"%H")

library(data.table)
ago5<-as.data.table(ago5)
ago5$FlowRange<-cut(ago5$`BP1 Bomb Contador-Caudal actua (m3/h)`, breaks=seq(0,360,10), include.lowest = TRUE)

ago5<-ago5[,AvPress:=mean(`BP1 Pressao Bombagem (bar)`, na.rm=TRUE), by="FlowRange"]

flowPressure<-ago5[,c("AvPress", "FlowRange")]

flowPressure<-flowPressure[!duplicated(flowPressure)]
write_csv(flowPressure,"flowPressure.csv")
```

